### ISSUE TITLE
When rotation screen, popup field has been broken.

### ISSUE THREAD

**Issue by closer27** [cacmartinez/CCMPopup#1]
Hi, I've used your source well.
One day I found some problem that rotation after the popup view popped 
I found 2 problem.

the one is that after popup view popped, when I rotate screen, layout is broken.
![ios simulator screen shot mar 12 2015 1 45 19 pm](https://cloud.githubusercontent.com/assets/1941113/6612390/ece2e0dc-c8be-11e4-810f-652831d6c458.png)

another is, as you see, that when the screen is landscape, if I pop the popup view, the background view which blurred doesn't cover all of area. it is also occurred in case of problem 1 which I mentioned.
and I also found that the blurred background view (left side on screenshot) is not corrected blurred about current screen as the landscape screen shown. I think that blurring is processed by portrait screen.
![ios simulator screen shot mar 12 2015 1 51 32 pm](https://cloud.githubusercontent.com/assets/1941113/6612391/ed2092c4-c8be-11e4-98e9-583dc4482534.png)

Thank you for providing good library. English is not my primary language, if you have a difficulty to read,  I'll write again. Thank you.

**Comment by cacmartinez** [comment]
Hi,

Thanks for your interest in my library, and for letting me know about these bugs. I have just finished fixing them, it should be working now. Please try the update, and feel free to let me know if any more bugs come up.

Cheers,
Carlos

**Comment by closer27** [comment]
Wow, how fast !!
It is worked very well now. 
Thanks a lot!!
