### ISSUE TITLE
Question : capture the event dismiss

### ISSUE THREAD

**Issue by ZebedeeTR** [cacmartinez/CCMPopup#2]
Hi. Thank you so much for this control.

I have a question.
I'm popup the view with code. And I did dismissableByTouchingBackground property to YES;
How do I capture the event dismiss when Touching Background?

**Comment by cacmartinez** [comment]
Hi,
Thanks for using my control. I am not sure what do you mean exactly. As I understood, you want to implement some code when the view has been dismissed, for this you could use apple methods of methods viewDidDisappear, viewWillDisappear of the controller that was presented, or the viewDidAppear, and viewWillAppear of the presenting controller. I don't know if this is what you were looking for, if not could you please be a little more specific?

**Comment by ZebedeeTR** [comment]
Thanks for your answer. I'm sorry for my English.
Actually, viewWillDisappear is work for me but, The following is what I want:

I'm getting some information from the modal(popup) view.
And I want to send this information to the base(parent) view. How can I do this?
How do I get ParentView from PopupView?

**Comment by cacmartinez** [comment]
For that you could implement your own delegate pattern in your popup view controller, and have methods that return the result to your original view controller when dismissing, or create a weak reference in the destination controller and assign it to the calling controller before presenting the popup controller
